### ISSUE TITLE
Make it possible to add custom text to DFilePicker

### ISSUE THREAD

**Issue by Bernardinyang** [DepositsTeam/ui-kit-vue#40]
![Screenshot 2024-03-19 at 12 28 39 PM](https://github.com/DepositsTeam/ui-kit-vue/assets/20227878/311bbae1-fe18-4c12-af0f-0e7c1e6bd1f6)

I need to be able to write my own text

**Comment by EricMcWinNer** [comment]
@Bernardinyang This is already possible today. This component supports a couple of slots.

- `icon`
- `default`

You should be able to do something like:


```
<d-file-picker>
   <p>I am some random text</p>
</d-file-picker>
